# Generated by Django 5.2.6 on 2025-09-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['progress']},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['progress']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
